## **Gradient Descent**

### **Installing Dependencies**

In [1]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

### **Importing Dataset**

In [2]:
X, y = make_regression(n_samples=100, n_features=2,  # type: ignore
                       n_targets=1, noise=80, random_state=2)

In [3]:
X[:5]

array([[ 0.18040981,  0.55316427],
       [-0.27617949, -0.51688389],
       [-0.46200535,  0.35088849],
       [ 0.39652016, -0.31461744],
       [-1.02141473,  0.4323957 ]])

In [4]:
y[:5]

array([ 86.40059546, 132.61681468, -60.80617313,  91.74404743,
       -99.18431535])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2)

### **Gradient Descent**

In [44]:
class GDRegressor:
    def __init__(self, batch_size: int, learning_rate: float = 0.01, epochs: int = 10) -> None:
        self.intercept_ = None
        self.coef_ = None
        self.batch_size: int = batch_size
        self.learning_rate: float = learning_rate
        self.epochs: int = epochs

    def fit(self, X_train, y_train):
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            np.random.shuffle(X_train)
            n_minibatches: int = int(np.ceil(X_train.shape[0] / self.batch_size))
            
            for j in range(n_minibatches):
                X_mini = X_train[j * self.batch_size : (j + 1) * self.batch_size, :]
                y_mini = y_train[j * self.batch_size : (j + 1) * self.batch_size]

                # print(X_mini.shape)
                # print(y_mini.shape)
                # print(self.coef_.shape)

                y_pred = np.dot(X_mini, self.coef_) + self.intercept_

                intercept_der = -2 * np.mean(y_mini - y_pred)
                self.intercept_ = self.intercept_ - (self.learning_rate * intercept_der)

                coef_der = -2 * np.mean(np.dot((y_mini - y_pred), X_mini))
                self.coef_ = self.coef_ - (self.learning_rate * coef_der)

    def predict(self, X_test):
        y_pred = np.dot(X_test, self.coef_) + self.intercept_
        return y_pred

In [45]:
lr = GDRegressor(batch_size=10)

In [46]:
lr.fit(X_train, y_train)

In [48]:
lr.coef_

array([2.99471805, 2.99471805])

In [49]:
lr.intercept_

-23.494094678909676

In [47]:
lr.predict(X_test)

array([-23.66509721, -27.20891834, -19.32061293, -21.68176527,
       -17.61753002, -19.41055844, -23.82685833, -24.84213762,
       -21.38573342, -24.97925109, -25.71445372, -17.319604  ,
       -18.34571829, -18.36751004, -21.29724714, -22.03941605,
       -23.24881912, -20.26798978, -24.21820592, -28.41290823])