## **Linear Regression**

#### **Installing Dependencies**

In [1]:
import numpy as np
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

#### **Importing Dataset**

In [2]:
X, y = make_regression(n_samples=100, n_features=2,  # type: ignore
                       n_targets=1, noise=80, random_state=2)

In [3]:
X[:5]

array([[ 0.18040981,  0.55316427],
       [-0.27617949, -0.51688389],
       [-0.46200535,  0.35088849],
       [ 0.39652016, -0.31461744],
       [-1.02141473,  0.4323957 ]])

In [4]:
y[:5]

array([ 86.40059546, 132.61681468, -60.80617313,  91.74404743,
       -99.18431535])

In [5]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=2)

#### **Linear Regression**

In [6]:
class LinearReg():
    def __init__(self):
        self.coef_ = None
        self.intercept_ = None

    def fit(self, X_train, y_train):
        X_train = np.insert(X_train, 0, values=1, axis=1)
        self.weights = np.linalg.inv(
            np.dot(X_train.T, X_train)).dot(X_train.T).dot(y_train)
        self.intercept_ = self.weights[0]
        self.coef_ = self.weights[1:]

    def predict(self, X_test):
        y_pred = X_test.dot(self.coef_) + self.intercept_
        return y_pred

In [7]:
lr = LinearReg()

In [8]:
lr.fit(X_train, y_train)

In [9]:
lr.coef_

array([41.17882219, 10.27760485])

In [10]:
lr.intercept_

-24.88359194044656

In [11]:
lr.predict(X_test)

array([-8.81289903e+00, -4.88953826e+01,  1.09527897e+01, -7.62684072e-02,
       -1.30299345e+01,  4.45240410e+01, -4.03021347e+01, -4.11185974e+01,
        1.42739713e+01, -9.59915759e+01, -5.81249556e+01,  2.10023433e+01,
        2.24745077e+01,  6.10595293e+00, -1.17693248e+01, -5.38436358e+01,
       -1.17888725e+01,  6.49997582e+01, -4.13204782e+00, -3.50862730e+01])